# sim_venue.py - simulated exchange for dry run testing
from __future__ import annotations

import logging
import random
import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Callable, Dict, List, Optional, Tuple

import config

logger = logging.getLogger("SimVenue")


# Data Classes

class OrderSide(Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderStatus(Enum):
    PENDING_NEW = "PENDING_NEW"      # Waiting for ack
    OPEN = "OPEN"                    # Resting in book
    PENDING_CANCEL = "PENDING_CANCEL"  # Cancel requested, can still fill
    FILLED = "FILLED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


class RejectReason(Enum):
    RATE_LIMIT = "RATE_LIMIT"
    MARGIN = "MARGIN"
    POST_ONLY_WOULD_TAKE = "POST_ONLY_WOULD_TAKE"


@dataclass
class SimOrder:
    """A resting order in the simulated venue."""
    oid: str
    side: OrderSide
    price: float
    size: float
    remaining: float
    status: OrderStatus = OrderStatus.PENDING_NEW
    is_reduce_only: bool = False
    is_post_only: bool = True

    # Timestamps (seconds since epoch)
    created_at: float = 0.0
    ack_at: float = 0.0           # When order will be acked
    cancel_requested_at: float = 0.0
    cancel_ack_at: float = 0.0    # When cancel will be acked

    # Queue position tracking
    queue_ahead: float = 0.0      # Estimated volume ahead of us in queue
    price_level_size: float = 0.0  # Total size at price level when we joined

    # Reject info
    reject_reason: Optional[RejectReason] = None


@dataclass
class FillEvent:
    """A fill generated by the simulated venue."""
    oid: str
    side: OrderSide
    price: float
    size: float
    remaining: float
    is_maker: bool
    timestamp: float
    adverse_penalty_bps: float = 0.0  # Bps the price moved against you post-fill


@dataclass
class RejectEvent:
    """An order rejection."""
    oid: str
    reason: RejectReason
    timestamp: float


# Config Helpers

def _cfg(name: str, default):
    """Get config value with fallback."""
    return getattr(config, name, default)


# Simulated Venue

class SimulatedVenue:
    """
    A realistic simulated exchange for dry-run paper trading.

    Usage:
        venue = SimulatedVenue()
        venue.on_tick(bids, asks, mid_price, now)
        fills, rejects = venue.submit_orders(desired_buy_orders, desired_sell_orders, now)
        # Apply fills to sim_position, sim_cash, etc.
    """

    def __init__(self, seed: Optional[int] = None):
        """
        Args:
            seed: RNG seed for reproducible backtests. None = non-deterministic.
        """
        self._rng = random.Random(seed)

        # Resting orders keyed by oid
        self._orders: Dict[str, SimOrder] = {}

        # Previous L2 snapshot for delta calculation
        self._prev_bids: List[List[float]] = []
        self._prev_asks: List[List[float]] = []

        # Rate-limit budget (simple token bucket)
        self._rate_tokens: float = _cfg("SIM_RATE_LIMIT_PER_MIN", 1200)
        self._rate_last_refill: float = 0.0

        # Config cache
        self._order_ack_ms: float = _cfg("SIM_ORDER_ACK_MS", 80)
        self._cancel_ack_ms: float = _cfg("SIM_CANCEL_ACK_MS", 120)
        self._reject_prob_rate: float = _cfg("SIM_REJECT_PROB_RATE_LIMIT", 0.002)
        self._reject_prob_margin: float = _cfg("SIM_REJECT_PROB_MARGIN", 0.001)
        self._taker_slippage_bps: float = _cfg("SIM_TAKER_SLIPPAGE_EXTRA_BPS", 0.5)
        self._adverse_select_bps: float = _cfg("SIM_ADVERSE_SELECT_BPS", 0.5)
        self._adverse_mode: str = _cfg("SIM_ADVERSE_SELECT_MODE", "immediate")
        self._partial_chunk_pct: float = _cfg("SIM_PARTIAL_CHUNK_PCT", 0.5)

        # Tracking
        self.total_fills = 0
        self.total_rejects = 0

    # ----------------------------------------------------------
    # Public API
    # ----------------------------------------------------------

    def reset(self):
        """Clear all orders (e.g., between backtest runs)."""
        self._orders.clear()
        self._prev_bids.clear()
        self._prev_asks.clear()
        self.total_fills = 0
        self.total_rejects = 0

    def on_tick(
        self,
        bids: List[List[float]],
        asks: List[List[float]],
        mid_price: float,
        now: float,
    ) -> Tuple[List[FillEvent], List[RejectEvent]]:
        """
        Called each tick with the new L2 snapshot.
        Processes pending acks, cancel acks, and generates fills from queue consumption.

        Returns:
            (fills, rejects) generated this tick.
        """
        fills: List[FillEvent] = []
        rejects: List[RejectEvent] = []

        # 1. Refill rate-limit tokens
        self._refill_rate_tokens(now)

        # 2. Process pending new orders (ack them)
        for o in list(self._orders.values()):
            if o.status == OrderStatus.PENDING_NEW and now >= o.ack_at:
                # Check for post-only would-take rejection
                if o.is_post_only:
                    would_cross = (
                        (o.side == OrderSide.BUY and asks and o.price >= asks[0][0])
                        or (o.side == OrderSide.SELL and bids and o.price <= bids[0][0])
                    )
                    if would_cross:
                        o.status = OrderStatus.REJECTED
                        o.reject_reason = RejectReason.POST_ONLY_WOULD_TAKE
                        rejects.append(RejectEvent(o.oid, o.reject_reason, now))
                        self.total_rejects += 1
                        continue

                # Order is now open / resting
                o.status = OrderStatus.OPEN
                # Initialize queue position from current book
                o.queue_ahead, o.price_level_size = self._calc_initial_queue(o, bids, asks)

        # 3. Process pending cancels (ack them)
        for o in list(self._orders.values()):
            if o.status == OrderStatus.PENDING_CANCEL and now >= o.cancel_ack_at:
                # Cancel succeeds (unless already filled this tick)
                if o.remaining > 0:
                    o.status = OrderStatus.CANCELLED
                else:
                    o.status = OrderStatus.FILLED

        # 4. Estimate consumed volume at each price level and generate fills
        consumed_bid, consumed_ask = self._estimate_consumed_volume(bids, asks)
        fills.extend(self._process_queue_fills(consumed_bid, consumed_ask, mid_price, now))

        # 5. Save current book for next delta
        self._prev_bids = [list(lvl) for lvl in bids]
        self._prev_asks = [list(lvl) for lvl in asks]

        # 6. Prune terminal orders
        self._prune_terminal_orders()

        return fills, rejects

    def submit_orders(
        self,
        buy_orders: List,  # Objects with .price, .size, .reduce_only, etc.
        sell_orders: List,
        now: float,
        margin_available: float = float("inf"),
    ) -> Tuple[List[FillEvent], List[RejectEvent]]:
        """
        Submit new desired orders (from strategy).
        Diffs against current resting orders and places/cancels as needed.

        Returns:
            (fills, rejects) for any taker orders that execute immediately.
        """
        fills: List[FillEvent] = []
        rejects: List[RejectEvent] = []

        # Build desired set
        desired_buys = {self._order_key(o, OrderSide.BUY): o for o in buy_orders}
        desired_sells = {self._order_key(o, OrderSide.SELL): o for o in sell_orders}

        # Cancel orders no longer desired
        for o in list(self._orders.values()):
            if o.status in (OrderStatus.OPEN, OrderStatus.PENDING_NEW, OrderStatus.PARTIALLY_FILLED):
                key = (o.side.value, round(o.price, 6))
                if o.side == OrderSide.BUY and key not in [(OrderSide.BUY.value, round(d.price, 6)) for d in buy_orders]:
                    self._request_cancel(o, now)
                elif o.side == OrderSide.SELL and key not in [(OrderSide.SELL.value, round(d.price, 6)) for d in sell_orders]:
                    self._request_cancel(o, now)

        # Place new orders not already resting
        existing_keys = {
            (o.side.value, round(o.price, 6))
            for o in self._orders.values()
            if o.status in (OrderStatus.OPEN, OrderStatus.PENDING_NEW, OrderStatus.PARTIALLY_FILLED, OrderStatus.PENDING_CANCEL)
        }

        for o in buy_orders:
            key = (OrderSide.BUY.value, round(o.price, 6))
            if key not in existing_keys:
                f, r = self._place_order(OrderSide.BUY, o.price, o.size, getattr(o, 'reduce_only', False), now, margin_available)
                if f:
                    fills.append(f)
                if r:
                    rejects.append(r)

        for o in sell_orders:
            key = (OrderSide.SELL.value, round(o.price, 6))
            if key not in existing_keys:
                f, r = self._place_order(OrderSide.SELL, o.price, o.size, getattr(o, 'reduce_only', False), now, margin_available)
                if f:
                    fills.append(f)
                if r:
                    rejects.append(r)

        return fills, rejects

    def get_open_orders(self) -> List[SimOrder]:
        """Return list of currently open/pending orders."""
        return [
            o for o in self._orders.values()
            if o.status in (OrderStatus.OPEN, OrderStatus.PENDING_NEW, OrderStatus.PARTIALLY_FILLED, OrderStatus.PENDING_CANCEL)
        ]

    def cancel_all(self, now: float):
        """Request cancel on all open orders."""
        for o in list(self._orders.values()):
            if o.status in (OrderStatus.OPEN, OrderStatus.PENDING_NEW, OrderStatus.PARTIALLY_FILLED):
                self._request_cancel(o, now)

    # ----------------------------------------------------------
    # Internal Helpers
    # ----------------------------------------------------------

    def _order_key(self, o, side: OrderSide) -> Tuple[str, float]:
        return (side.value, round(o.price, 6))

    def _place_order(
        self,
        side: OrderSide,
        price: float,
        size: float,
        reduce_only: bool,
        now: float,
        margin_available: float,
    ) -> Tuple[Optional[FillEvent], Optional[RejectEvent]]:
        """
        Place a new order. May reject or immediately fill (taker).
        """
        oid = str(uuid.uuid4())[:8]

        # Stochastic rate-limit rejection
        if self._rng.random() < self._reject_prob_rate or self._rate_tokens <= 0:
            self.total_rejects += 1
            return None, RejectEvent(oid, RejectReason.RATE_LIMIT, now)

        # Stochastic margin rejection (very simplified)
        notional = price * size
        if self._rng.random() < self._reject_prob_margin or notional > margin_available:
            self.total_rejects += 1
            return None, RejectEvent(oid, RejectReason.MARGIN, now)

        # Consume a rate token
        self._rate_tokens -= 1

        order = SimOrder(
            oid=oid,
            side=side,
            price=price,
            size=size,
            remaining=size,
            is_reduce_only=reduce_only,
            created_at=now,
            ack_at=now + self._order_ack_ms / 1000.0,
        )
        self._orders[oid] = order

        # Note: Taker fills are handled in on_tick after ack
        return None, None

    def _request_cancel(self, o: SimOrder, now: float):
        """Request cancellation (with latency)."""
        if o.status in (OrderStatus.PENDING_CANCEL, OrderStatus.CANCELLED, OrderStatus.FILLED, OrderStatus.REJECTED):
            return
        o.status = OrderStatus.PENDING_CANCEL
        o.cancel_requested_at = now
        o.cancel_ack_at = now + self._cancel_ack_ms / 1000.0

    def _calc_initial_queue(
        self,
        order: SimOrder,
        bids: List[List[float]],
        asks: List[List[float]],
    ) -> Tuple[float, float]:
        """
        Estimate initial queue_ahead when order is acked.
        We assume we join at the back of the queue at our price level,
        plus all volume at better prices.
        """
        queue_ahead = 0.0
        level_size = 0.0

        if order.side == OrderSide.BUY:
            # Better prices = higher bids
            for lvl in bids:
                px, sz = lvl[0], lvl[1]
                if px > order.price:
                    queue_ahead += sz
                elif abs(px - order.price) < 1e-9:
                    queue_ahead += sz  # We're at the back
                    level_size = sz
                    break
        else:
            # Better prices = lower asks
            for lvl in asks:
                px, sz = lvl[0], lvl[1]
                if px < order.price:
                    queue_ahead += sz
                elif abs(px - order.price) < 1e-9:
                    queue_ahead += sz
                    level_size = sz
                    break

        return queue_ahead, level_size

    def _estimate_consumed_volume(
        self,
        bids: List[List[float]],
        asks: List[List[float]],
    ) -> Tuple[Dict[float, float], Dict[float, float]]:
        """
        Estimate how much volume was consumed at each price level by comparing
        the current snapshot to the previous snapshot.

        Returns:
            (consumed_bid_by_price, consumed_ask_by_price)
        """
        consumed_bid: Dict[float, float] = {}
        consumed_ask: Dict[float, float] = {}

        prev_bid_map = {round(lvl[0], 6): lvl[1] for lvl in self._prev_bids}
        prev_ask_map = {round(lvl[0], 6): lvl[1] for lvl in self._prev_asks}
        curr_bid_map = {round(lvl[0], 6): lvl[1] for lvl in bids}
        curr_ask_map = {round(lvl[0], 6): lvl[1] for lvl in asks}

        # Bid side: if size decreased, assume it was consumed (trades hit bids)
        for px, prev_sz in prev_bid_map.items():
            curr_sz = curr_bid_map.get(px, 0.0)
            delta = prev_sz - curr_sz
            if delta > 0:
                consumed_bid[px] = delta

        # Ask side: if size decreased, assume it was consumed (trades lifted asks)
        for px, prev_sz in prev_ask_map.items():
            curr_sz = curr_ask_map.get(px, 0.0)
            delta = prev_sz - curr_sz
            if delta > 0:
                consumed_ask[px] = delta

        return consumed_bid, consumed_ask

    def _process_queue_fills(
        self,
        consumed_bid: Dict[float, float],
        consumed_ask: Dict[float, float],
        mid_price: float,
        now: float,
    ) -> List[FillEvent]:
        """
        Decrement queue_ahead for each open order based on consumed volume.
        Generate fills when queue_ahead reaches zero.
        """
        fills: List[FillEvent] = []

        for o in list(self._orders.values()):
            if o.status not in (OrderStatus.OPEN, OrderStatus.PARTIALLY_FILLED, OrderStatus.PENDING_CANCEL):
                continue

            px_key = round(o.price, 6)

            # Get consumed volume at our price (+ all better prices for safety)
            if o.side == OrderSide.BUY:
                consumed = sum(v for p, v in consumed_bid.items() if p >= o.price)
            else:
                consumed = sum(v for p, v in consumed_ask.items() if p <= o.price)

            if consumed <= 0:
                continue

            # Decrement queue
            o.queue_ahead = max(0.0, o.queue_ahead - consumed)

            # If queue cleared, we get filled
            if o.queue_ahead <= 0 and o.remaining > 0:
                # Partial or full fill based on remaining consumed
                fill_size = min(o.remaining, consumed * self._partial_chunk_pct) if self._partial_chunk_pct < 1.0 else o.remaining
                fill_size = max(fill_size, o.remaining * 0.1)  # At least 10%
                fill_size = min(fill_size, o.remaining)

                o.remaining -= fill_size
                if o.remaining <= 0:
                    o.status = OrderStatus.FILLED
                else:
                    o.status = OrderStatus.PARTIALLY_FILLED

                # Adverse selection penalty
                adverse_bps = self._calc_adverse_penalty(o.side, mid_price)

                fills.append(FillEvent(
                    oid=o.oid,
                    side=o.side,
                    price=o.price,
                    size=fill_size,
                    remaining=o.remaining,
                    is_maker=True,
                    timestamp=now,
                    adverse_penalty_bps=adverse_bps,
                ))
                self.total_fills += 1

                logger.debug(
                    f"SIM FILL: {o.side.value} {fill_size:.4f} @ {o.price:.4f} "
                    f"(remaining={o.remaining:.4f}, adverse={adverse_bps:.1f}bps)"
                )

        return fills

    def _calc_adverse_penalty(self, side: OrderSide, mid_price: float) -> float:
        """
        Calculate adverse selection penalty in bps.
        When you get filled as maker, price often moves against you.
        """
        base_bps = self._adverse_select_bps
        # Add some randomness
        noise = self._rng.gauss(0, base_bps * 0.3)
        penalty = max(0, base_bps + noise)
        return penalty

    def _refill_rate_tokens(self, now: float):
        """Token bucket refill for rate limiting."""
        max_tokens = _cfg("SIM_RATE_LIMIT_PER_MIN", 1200)
        if self._rate_last_refill == 0:
            self._rate_last_refill = now
            self._rate_tokens = max_tokens
            return

        elapsed = now - self._rate_last_refill
        refill = (elapsed / 60.0) * max_tokens
        self._rate_tokens = min(max_tokens, self._rate_tokens + refill)
        self._rate_last_refill = now

    def _prune_terminal_orders(self):
        """Remove orders in terminal states to prevent memory leak."""
        terminal = [
            oid for oid, o in self._orders.items()
            if o.status in (OrderStatus.FILLED, OrderStatus.CANCELLED, OrderStatus.REJECTED)
        ]
        for oid in terminal:
            del self._orders[oid]


# Taker Slippage Helper

def compute_taker_fill_price(
    side: str,
    size: float,
    bids: List[List[float]],
    asks: List[List[float]],
    extra_slippage_bps: float = 0.5,
) -> Tuple[float, float]:
    """
    Compute VWAP fill price for a taker order by walking the book.

    Args:
        side: "BUY" or "SELL"
        size: Order size
        bids: [[price, size], ...]
        asks: [[price, size], ...]
        extra_slippage_bps: Additional slippage to add (market impact / latency)

    Returns:
        (fill_price, filled_size) - filled_size may be < size if book is thin.
    """
    levels = asks if side == "BUY" else bids
    remaining = size
    total_value = 0.0
    filled = 0.0

    for lvl in levels:
        px, sz = lvl[0], lvl[1]
        take = min(remaining, sz)
        total_value += px * take
        filled += take
        remaining -= take
        if remaining <= 0:
            break

    if filled <= 0:
        return 0.0, 0.0

    vwap = total_value / filled

    # Apply extra slippage
    slip = vwap * (extra_slippage_bps / 10000.0)
    if side == "BUY":
        vwap += slip
    else:
        vwap -= slip

    return vwap, filled
